poll_site/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    # path('', include('polls.urls')),
    # path('test/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

poll_site/mysite/polls/urls.py
from django.urls import path
from . import views

# Namespacing URL names

app_name = "polls"

urlpatterns = [
    # /polls/
    path('', views.index, name="index"),
    # /polls/5/
    path('<int:question_id>/', views.detail, name="detail"),
    # /polls/5/results
    path('<int:question_id>/results/', views.results, name="results"),
    # /polls/5/vote
    path('<int:question_id>/vote/', views.vote, name="vote"),
]

poll_site/mysite/polls/models.py
import datetime

from django.utils import timezone
from django.db import models

class   Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class   Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

poll_site/mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from .models import Question
# from django.template import loader

def index(request):
    latest_questions = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_questions" : latest_questions}
    return HttpResponse(render(request, "polls/index.html", context))

def detail(request, question_id):
    # try :
    #     q = Question.objects.get(pk=question_id)
    # except Question.DoesNotExist:
    #     raise Http404('Questions does not exist')
    q = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", { "question" : q })

def results(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

def vote(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)

poll_site/mysite/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>{{ question.question_text }}</h2>
    <ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }}</li>
    {% endfor %}
    </ul>
</body>
</html>

poll_site/mysite/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if latest_questions %}
        <ul>
        {% for q in latest_questions %}
{% comment %} <li><a href="/polls/{{ q.id }}/">{{ q.question_text }}</a></li> {% endcomment %}
            <li><a href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available</p>
    {% endif %}
</body>
</html>